const foodData = {
  "Udupi": ["Tea", "Hot coffee", "Cold coffee", "Banana shake", "Mango shake", "Oreo shake", "Lassi", "Cold drinks", "Ice cream", "Samosa", "Bread Pakoda", "Veg Sandwich", "Burger", "Grilled Sandwich", "Maggi", "Chole bhature", "Aloo Puri", "Vada Sambar", "Idli Sambar", "Masala dosa", "Paneer Dosa", "Plain Dosa", "Chole chawal", "Rajma Chawal", "Uttapam", "Pav bhaji", "Chowmein", "Spring roll", "Chilli potato", "Chilli paneer", "French fries", "Manchurian", "Aloo Paratha", "Aloo Pyaz", "Paneer Paratha"],
  "Bistro": ["Ice mocha coffee", "Cold coffee", "Iced Vietnamese Coffee", "Hazelnut Cold Coffee", "Caramel Frappe Coffee", "Irish Frappe Coffee", "Nutella Frappe Coffee", "Tiramisu frappe Coffee", "Brownie Frappe Coffee", "Cappucino Coffee", "Mocha coffee", "White Mocha coffee", "Hazelnut coffee", "Irish Coffee", "Carmelo Coffee", "Classic Mocha Coffee", "Tiramisu Coffee", "Classic Mint Mojito", "Orange mojito", "Peach mojito", "Green Apple Mojito", "Strawberry mojito", "Watermelon mojito", "Ice tea (lemon/peach/watermelon/strawberry)", "Fruit beer", "Lime soda", "Blue lagoon", "Hot chocolate fudge", "Brownie fudge", "Hot brownie", "brownie with ice cream", "Hot chocolate", "Belgium hot chocolate", "Oreo shake", "Kitkat shake", "Brownie Cookie shake", "Ferrero rocher shake", "Nutella Crunch Shake", "Avacado shake", "Vanilla shake", "Chocolate shake", "Strawberry shake", "Butter scotch shake", "Mango shake", "Coconut shake", "Black currant shake", "Baked Nachos", "Garlic Toast", "Veg Burger", "Paneer burger", "Cheese pizza", "Veg Pizza", "Cheese n Corn Pizza", "Paneer Makhni pizza", "Salted Fries", "Peri peri fries", "Cheesy fries", "Cheese baked fries", "Veg grilled sandwich", "Cheese n corn sandwich", "Paneer makhni sandwich"],
  "HIMS": ["Espresso coffee", "Americano coffee", "Cappucino Coffee", "Cafe late coffee", "Vanilla cafe latte coffee", "Hazelnut cafe latte coffee", "Caramel cafe latte coffee", "cafe mocha latte coffee", "hot chocolate", "Cold coffee", "choco frappe cold coffee", "crunchy hazelnut cold coffee", "caramel frappe cold coffee", "Tiramisu frappe cold coffee", "Lemon iced tea", "Peach apricot iced tea", "Lemon and strawberry iced tea", "Iced americano coffee", "Iced latte coffee", "Iced mocha coffee", "iced caramel latte coffee", "iced hazelnut latte coffee", "iced vanilla coffee", "iced vietnamese Coffee", "iced spanish coffee", "Raspberry strawberry boba tea", "Passion fruit boba tea", "Fresh lime soda", "Masala lemonade", "Mojito", "Watermelon mojito", "kiwi mojito", "strawberry daiquiri", "passionfruit mojito", "Mango lassi", "Aam panna twister", "Peanut butter oats smoothie", "Berry smoothie", "Banana smoothie", "Sattu drink", "French vanilla peanut shake", "Kitkat shake", "Belgian chocolate shake", "Choco banana shake", "Tiramisu shake", "Blurberry cheesecake shake", "Pina colada shake", "Strawberry bubblegum shake", "Cereal with milk", "Museli with milk", "museli with curd", "millet upma", "masala oats", "Veg club sandwich", "Spicy potato sandwich", "Chilli tofu sandwich", "Paneer sandwich", "Veg wrap", "Spicy potato wrap", "chilli tofu wrap", "falafel wrap", "Barbeque paneer wrap", "chaap wrap", "French fries", "peri peri fries", "garlic fries", "Cheesey fries", "pizza pockets", "arrabiata pasta", "Alfredo pasta", "pesto pasta", "mixed sauce pasta", "crispy veg burger", "spicy paneer burger", "mexican salsa burger"],
  "DelTech Cafe": ["Veg Momos (Half)", "Veg Momos (Full)", "Veg Gravy Momos (Half)", "Veg Gravy Momos (Full)", "Veg Kurkure Momos (Half)", "Veg Kurkure Momos (Full)", "Veg Afghani Momos (Half)", "Veg Afghani Momos (Full)", "Paneer Momos (Half)", "Paneer Momos (Full)", "Paneer Gravy Momos (Half)", "Paneer Gravy Momos (Full)", "Paneer Kurkure Momos (Half)", "Paneer Kurkure Momos (Full)", "Paneer Afghani Momos (Half)", "Paneer Afghani Momos (Full)", "Chicken Momos (Half)", "Chicken Momos (Full)", "Chicken Gravy Momos (Half)", "Chicken Gravy Momos (Full)", "Chicken Kurkure Momos (Half)", "Chicken Kurkure Momos (Full)", "Chicken Afghani Momos (Half)", "Chicken Afghani Momos (Full)", "Masala Dosa", "Paneer Dosa", "Mix Veg Plump", "Egg Dosa", "Schezwan Dosa", "White Sauce Pasta", "Red Sauce Pasta", "Mix Sauce Pasta", "Rajma Rice", "Veg Fried Rice", "Paneer Fried Rice", "Egg Fried Rice", "Chips", "Cold Drink", "Biscuit", "Veg Roll", "Egg Roll (1 Egg)", "Egg Roll (2 Eggs)", "Paneer Roll", "Chicken Roll", "Chicken Roll (2 Eggs)", "Chicken Roll (2 Eggs + 2 Chicken)", "Cold Coffee", "Oreo Shake", "Banana Shake", "Chocolate Shake", "Butter Scotch Shake", "Tea", "Coffee", "Samosa", "Bread Pakoda", "Aloo Patty", "Paneer Patty", "Veg Sandwich", "Grilled Sandwich", "Burger", "Brownie", "Aloo Paratha", "Paneer Paratha", "Mix Paratha", "Egg Paratha", "Veg Maggi", "Egg Maggi", "Veg Chowmein", "Singapuri Chowmein", "Egg Chowmein", "Chilli Potato", "Pav Bhaji"],
  "HPMC": ["Idli", "Dosa", "Vada", "Sambar"],
  "Amul": ["Thali", "Noodles", "Lemonade"],
  "Dosa Plaza": ["Pav Bhaji", "Pani Puri", "Chai"],
  "Dazzledine": ["Tacos", "Ice Cream", "Wrap", "Milkshake"],
  "KitKat Zone": ["Tacos", "Ice Cream", "Wrap", "Milkshake"],
  "Nescafe": ["Tacos", "Ice Cream", "Wrap", "Milkshake"],
  "Raydee Cafe": ["Tacos", "Ice Cream"]
};

function getRandomFood() {
  const places = Object.keys(foodData);
  const randomPlace = places[Math.floor(Math.random() * places.length)];
  const foods = foodData[randomPlace];
  const randomFood = foods[Math.floor(Math.random() * foods.length)];
  return { place: randomPlace, food: randomFood };
}

function suggestFood() {
  const suggestion = getRandomFood();
  const resultElement = document.getElementById("result");
  resultElement.textContent = `How about "${suggestion.food}" from ${suggestion.place}?`;
}

document.getElementById("generateButton").addEventListener("click", suggestFood);
