const foodData = {
  "Udupi": ["Tea", "Hot coffee", "Cold coffee", "Banana shake", "Mango shake", "Oreo shake", "Lassi", "Cold drinks", "Ice cream", "Samosa", "Bread Pakoda", "Veg Sandwich", "Burger", "Grilled Sandwich", "Maggi", "Chole bhature", "Aloo Puri", "Vada Sambar", "Idli Sambar", "Masala dosa", "Paneer Dosa", "Plain Dosa", "Chole chawal", "Rajma Chawal", "Uttapam", "Pav bhaji", "Chowmein", "Spring roll", "Chilli potato", "Chilli paneer", "French fries", "Manchurian", "Aloo Paratha", "Aloo Pyaz", "Paneer Paratha"],
  "Bistro": ["Ice mocha coffee", "Cold coffee", "Iced Vietnamese Coffee", "Hazelnut Cold Coffee", "Caramel Frappe Coffee", "Irish Frappe Coffee", "Nutella Frappe Coffee", "Tiramisu frappe Coffee", "Brownie Frappe Coffee", "Cappucino Coffee", "Mocha coffee", "White Mocha coffee", "Hazelnut coffee", "Irish Coffee", "Carmelo Coffee", "Classic Mocha Coffee", "Tiramisu Coffee", "Classic Mint Mojito", "Orange mojito", "Peach mojito", "Green Apple Mojito", "Strawberry mojito", "Watermelon mojito", "Ice tea (lemon/peach/watermelon/strawberry)", "Fruit beer", "Lime soda", "Blue lagoon", "Hot chocolate fudge", "Brownie fudge", "Hot brownie", "brownie with ice cream", "Hot chocolate", "Belgium hot chocolate", "Oreo shake", "Kitkat shake", "Brownie Cookie shake", "Ferrero rocher shake", "Nutella Crunch Shake", "Avacado shake", "Vanilla shake", "Chocolate shake", "Strawberry shake", "Butter scotch shake", "Mango shake", "Coconut shake", "Black currant shake", "Baked Nachos", "Garlic Toast", "Veg Burger", "Paneer burger", "Cheese pizza", "Veg Pizza", "Cheese n Corn Pizza", "Paneer Makhni pizza", "Salted Fries", "Peri peri fries", "Cheesy fries", "Cheese baked fries", "Veg grilled sandwich", "Cheese n corn sandwich", "Paneer makhni sandwich"],
  "HIMS": ["Espresso coffee", "Americano coffee", "Cappucino Coffee", "Cafe late coffee", "Vanilla cafe latte coffee", "Hazelnut cafe latte coffee", "Caramel cafe latte coffee", "cafe mocha latte coffee", "hot chocolate", "Cold coffee", "choco frappe cold coffee", "crunchy hazelnut cold coffee", "caramel frappe cold coffee", "Tiramisu frappe cold coffee", "Lemon iced tea", "Peach apricot iced tea", "Lemon and strawberry iced tea", "Iced americano coffee", "Iced latte coffee", "Iced mocha coffee", "iced caramel latte coffee", "iced hazelnut latte coffee", "iced vanilla coffee", "iced vietnamese Coffee", "iced spanish coffee", "Raspberry strawberry boba tea", "Passion fruit boba tea", "Fresh lime soda", "Masala lemonade", "Mojito", "Watermelon mojito", "kiwi mojito", "strawberry daiquiri", "passionfruit mojito", "Mango lassi", "Aam panna twister", "Peanut butter oats smoothie", "Berry smoothie", "Banana smoothie", "Sattu drink", "French vanilla peanut shake", "Kitkat shake", "Belgian chocolate shake", "Choco banana shake", "Tiramisu shake", "Blurberry cheesecake shake", "Pina colada shake", "Strawberry bubblegum shake", "Cereal with milk", "Museli with milk", "museli with curd", "millet upma", "masala oats", "Veg club sandwich", "Spicy potato sandwich", "Chilli tofu sandwich", "Paneer sandwich", "Veg wrap", "Spicy potato wrap", "chilli tofu wrap", "falafel wrap", "Barbeque paneer wrap", "chaap wrap", "French fries", "peri peri fries", "garlic fries", "Cheesey fries", "pizza pockets", "arrabiata pasta", "Alfredo pasta", "pesto pasta", "mixed sauce pasta", "crispy veg burger", "spicy paneer burger", "mexican salsa burger"],
  "DelTech Cafe": ["Veg Momos (Half)", "Veg Momos (Full)", "Veg Gravy Momos (Half)", "Veg Gravy Momos (Full)", "Veg Kurkure Momos (Half)", "Veg Kurkure Momos (Full)", "Veg Afghani Momos (Half)", "Veg Afghani Momos (Full)", "Paneer Momos (Half)", "Paneer Momos (Full)", "Paneer Gravy Momos (Half)", "Paneer Gravy Momos (Full)", "Paneer Kurkure Momos (Half)", "Paneer Kurkure Momos (Full)", "Paneer Afghani Momos (Half)", "Paneer Afghani Momos (Full)", "Chicken Momos (Half)", "Chicken Momos (Full)", "Chicken Gravy Momos (Half)", "Chicken Gravy Momos (Full)", "Chicken Kurkure Momos (Half)", "Chicken Kurkure Momos (Full)", "Chicken Afghani Momos (Half)", "Chicken Afghani Momos (Full)", "Masala Dosa", "Paneer Dosa", "Mix Veg Plump", "Egg Dosa", "Schezwan Dosa", "White Sauce Pasta", "Red Sauce Pasta", "Mix Sauce Pasta", "Rajma Rice", "Veg Fried Rice", "Paneer Fried Rice", "Egg Fried Rice", "Chips", "Cold Drink", "Biscuit", "Veg Roll", "Egg Roll (1 Egg)", "Egg Roll (2 Eggs)", "Paneer Roll", "Chicken Roll", "Chicken Roll (2 Eggs)", "Chicken Roll (2 Eggs + 2 Chicken)", "Cold Coffee", "Oreo Shake", "Banana Shake", "Chocolate Shake", "Butter Scotch Shake", "Tea", "Coffee", "Samosa", "Bread Pakoda", "Aloo Patty", "Paneer Patty", "Veg Sandwich", "Grilled Sandwich", "Burger", "Brownie", "Aloo Paratha", "Paneer Paratha", "Mix Paratha", "Egg Paratha", "Veg Maggi", "Egg Maggi", "Veg Chowmein", "Singapuri Chowmein", "Egg Chowmein", "Chilli Potato", "Pav Bhaji"],
  "HPMC": ["Mosambi Juice", "Mix Juice", "Carrot Juice", "Pineapple Juice", "Orange Juice", "Banana Shake", "Mango Shake", "Chikku Shake", "Papaya Shake", "Chocolate Shake", "Vanilla Shake", "Strawberry Shake", "Butter Scotch", "Peanut Butter", "Cold Coffee", "Kit-Kat Shake", "Lassi", "Lemon Soda", "Fruits Chaat", "Khajur Shake"],
  "Stall at Amul": ["Veg Momos", "Paneer Momos", "Plane Maggi", "Vegetable Maggi", "Masala Maggi", "Butter Maggi", "Egg Maggi", "Chicken Maggi", "Bread Omelette", "Butter Omelette", "Chicken Omelette", "Veg Fried Rice", "Egg Fried Rice", "Chicken Fried Rice", "Veg Chowmin", "Egg Chowmin", "Chicken Chowmin", "Singapuri Chowmin", "Butter Bread", "Omelette", "Chowmin Roll", "Vegetable Roll", "Single Egg Roll", "Double Egg Roll", "Paneer Roll", "Double Paneer Roll", "Paneer Egg Roll", "Chicken Roll", "Egg Chicken Roll", "Double Chicken Roll", "Double Chicken Egg Roll", "Mix Roll"],
  "Dosa Plaza": ["Idli (2pc)", "Ghee Sambar Idli", "Medu Vada (2pc)", "Sambar Vada (2pc)", "Rasam Vada (2pc)", "Rasam (with papad)", "Upma with Papad", "Upma (8am to 12pm)", "Podi Idli", "Coconut Shell Idli", "Garlic Roast Dosa", "Podi Roast Dosa", "Spicy Chutney Dosa", "Prem Roast Dosa", "Chocolate Dosa", "Jam Roast Dosa", "Cheese Roast Dosa", "Paper Ghee Roast Dosa", "Paper Roast Masala Dosa (4ft)", "Maharaja Masala Dosa", "Prem Roast Masala Dosa", "Sada Dosa", "Mysore Sada Dosa", "Ghee Roast Dosa", "Rava Dosa", "Cheese Sada Dosa", "Rocket Mysore Dosa", "Onion Rava Dosa", "Onion Roast Dosa", "Schezwan Sada Dosa", "Jini Dosa", "Pepper Chilli Roast Dosa", "Masala Dosa", "Mysore Masala Dosa", "Rava Masala Dosa", "Onion Rava Masala Dosa", "Pav Bhaji Dosa", "Spring Roll Dosa", "American Chopsuey Dosa", "Paneer Spring Roll Dosa", "Schezwan Dosa", "Chinese Delight Dosa", "Aloo Masala Dosa", "General Tso Dosa", "Aloo Roll Dosa", "Mixed Roll Dosa", "Pizza Dosa", "Cheese Delight Dosa", "Cheese Burst Dosa", "Double Cheese Burst Dosa", "Plain Uttappa", "Onion Uttappa", "Tomato Uttappa", "Masala Uttappa", "Mysore Uttappa", "Mix Veg. Uttappa", "Prem Uttappa (Mix Uttappa)", "Sambar Rice", "Puliyotharai Rice", "Tomato Rice", "Lemon Rice", "Curd Rice", "Rajma / Chole Rice", "Mumbai Pav Bhaji", "Cheese Pav Bhaji", "Paneer Pav Bhaji", "Butter Pav (1pc)", "Manchow Soup", "Sweet Corn Soup", "Veg Hot & Sour Soup", "Veg Clear Soup", "Tomato Soup", "Chinese Bhel", "Veg. Crispy", "Veg Spring Roll", "Veg Manchurian Dry", "Chilli Garlic Potato", "Veg Chilli Dry", "Soyabean Chilli Dry", "Soyabean Manchurian", "Honey Chilli Potato", "Mushroom 65", "Mushroom Chilli", "Paneer Chilli Dry", "Paneer Crispy", "Paneer Manchurian", "Idli Manchurian", "Idli Schezwan", "Veg Chilli Gravy", "Veg Manchurian Gravy", "Soyabean Chilli Gravy", "Paneer Chilli Gravy"],
  "Dazzledine": ["Veg. Thali", "Kadhi Rice", "Rajma Rice", "Chole Rice", "Pasta White/Pink Sauce", "Subway Sandwich", "Pav Bhaji", "Veg. Grilled Sandwich", "Cheese & Corn Grilled Sandwich", "Paneer Grilled Sandwich", "Veg. Maggi", "Cheese Maggi", "Veg. Kathi Rolls", "Peri Peri Fries with Cheese Dip", "Peri Peri Fries", "French Fries", "Bhel Puri", "Bun Maska", "Veg. Burger", "Cheese Burger", "Paneer Burger", "Mango Shake", "Banana Shake", "Chocolate Shake", "Vanilla Milk Shake", "Oreo Shake", "Cold Coffee", "Special Lassi", "Kulhad Chai", "Hot Coffee", "Virgin Mojito", "Mango Lassi", "Aloo Parantha & Curd", "Vada Pav", "Tomato Soup", "Hot & Sour Soup"],
  "KitKat Zone": ["KitKat Brownies", "KitKat Cookies", "KitKat Chocolate Truffle", "KitKat Croissants", "KitKat Pancakes (Dutch Chocolate)", "KitKat Pancakes (Honey, Peanut Butter)", "KitKat Shakes (Chocolate, Hazelnut, KitKat, Nescafé)", "Vegetable Masala / Aata Masala Maggi", "Butter Maggi / Sweet Corn Maggi", "Original Masala Maggi / Chilli Maggi", "Sweet Corn", "Classic Chilli Cheese / Masala A-E Maggi", "Tandoori Maggi", "Chilli Garlic Maggi", "Creamy Chilli Garlic Maggi", "Schezwan Maggi", "Peri Peri Maggi", "Cheese Garlic Maggi", "Special Fried Rice", "Chilli Garlic Fried Rice", "Cheese Oregano Maggi", "Biryani Maggi", "Manchurian Maggi", "Cheese Burst Maggi", "Makhani Gravy Maggi", "Kadhai Gravy Maggi", "Cheesy Egg Maggi Bowl", "Oregano Cheese Pazza", "Mushroom Pazza", "Delhi 6 Masala Pazza", "Tomato Pazza", "Masala Penne with Tomato", "Ginger Tea / Masala Tea / Cardamom Tea", "Lemon Tea / Hot Lemon Tea / Milk", "Caffè Mocha", "Hot Chocolate", "Ginger & Honey Tea", "Assam Tea", "Darjeeling Tea", "Espresso / Caramel / Hazelnut Cappuccino", "Hazelnut Latte", "Choco Frappe", "Irish / Caramel / Honey Frappe", "Mocha / Hazelnut Frappe", "KitKat Frappe", "Cold Coffee", "Cold Coffee + Ice Cream", "Tomato Soup", "Manchow Soup", "Lemon Iced Tea", "Special Masala / Mojito Iced Tea", "Passion Fruit Iced Tea / Peach Iced Tea"],
  "Nescafe": ["Regular Coffee", "Cappuccino", "Latte", "Café Mocha", "Americano", "Espresso", "Hot Chocolate", "Hazelnut Latte", "Cold Chocolate", "FRAPPE Mocha", "Frappe", "Hazelnut Frappe", "Irish Frappe", "Lemon Ice Tea", "Green Apple Ice Tea", "Masala Ice Tea", "Plain Maggi", "Double Masala Maggi", "Chili Garlic Maggi", "Atta Maggi", "Special Masala Maggi", "Butter Maggi", "Chilli Garlic Cheese Maggi", "Special Maggi", "Vegetables Maggi", "KitKat Shake", "Crunchy Shake", "Banana Shake", "Mango Shake"],
  "Raydee Cafe": ["Veg Burger", "Mexican Burger", "Raydee Special Double Patty Burger", "Paneer Crunch Burger", "Veg Loaded Sandwich", "Cheese Sandwich", "Aloo Sandwich", "Salted Fries", "Peri Peri Fries", "Cheesy Fries", "Plain Maggi", "Veg Maggi", "Cheese Maggi", "Butter Toast", "Veggie Strips", "Nuggets", "Potato Cheesy Shots", "Veg Crunchy Wrap", "Paneer Crunchy Wrap", "Dip for Fries", "Extra Cheese Slice", "Water Bottle", "Vanilla Muffin", "Blueberry Muffin", "Chocolate Muffin", "Doughnut", "Cake Jar", "Brownie", "Walnut Brownie"]
};

const imageData = {
  "Udupi": "images/udupi.jpg",
  "Bistro": "images/bistro.jpg",
  "HIMS": "images/hims.jpg",
  "DelTech Cafe": "images/deltechcafe.jpg",
  "HPMC": "images/hpmc.jpg",
  "Stall at Amul": "images/amul.jpg",
  "Dosa Plaza": "images/dosaplaza.jpg",
  "Dazzledine": "images/dazzledine.jpg",
  "KitKat Zone": "images/kitkat.jpg",
  "Nescafe": "images/nescafe.jpg",
  "Raydee Cafe": "images/raydee.jpg"
};

function getRandomFood() {
  const places = Object.keys(foodData);
  const randomPlace = places[Math.floor(Math.random() * places.length)];
  const foods = foodData[randomPlace];
  const randomFood = foods[Math.floor(Math.random() * foods.length)];
  return { place: randomPlace, food: randomFood };
}

function suggestFood() {
  const suggestion = getRandomFood();
  const resultElement = document.getElementById("result");
  resultElement.textContent = `How about "${suggestion.food}" from ${suggestion.place}?`;

  // Update image
  const canteenImage = document.getElementById("canteenImage");
  canteenImage.src = "images/" + result.place + ".jpg";
  // const imageElement = document.getElementById("canteenImage");
  // imageElement.src = imageData[suggestion.place];
  // imageElement.style.display = "block"; // show the image
}
document.getElementById("generateButton").addEventListener("click", suggestFood);
